CREATE DATABASE prj1;
USE prj1;

CREATE TABLE Board (
	id INT PRIMARY KEY AUTO_INCREMENT,
	title VARCHAR(255) NOT NULL,
    content VARCHAR(1000) NOT NULL
);

SELECT * FROM Board;
DELETE FROM Board
WHERE ID = 1;

ALTER TABLE Board
ADD COLUMN writer VARCHAR(255) NOT NULL;
DESC Board;

ALTER TABLE Board
ADD COLUMN inserted DATETIME NOT NULL DEFAULT NOW();
